# Generated by Django 6.0.7 on 2026-07-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_participant_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of participants allowed.'),
        ),
    ]
