# Generated by Django 6.0.7 on 2026-08-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_participant_address_participant_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=500, help_text='Maximum number of participants allowed.'),
        ),
    ]
