# Generated by Django 6.0.7 on 2026-08-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='offline_participants',
            field=models.PositiveIntegerField(default=0, help_text='Number of offline/manual participants.'),
        ),
    ]
