# Generated by Django 6.0.7 on 2026-08-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_offline_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='offline_participants',
        ),
        migrations.AddField(
            model_name='event',
            name='offline_absent',
            field=models.PositiveIntegerField(default=0, help_text='Number of offline participants who were absent.'),
        ),
        migrations.AddField(
            model_name='event',
            name='offline_present',
            field=models.PositiveIntegerField(default=0, help_text='Number of offline participants who attended.'),
        ),
    ]
