# Generated by Django 6.0.7 on 2026-08-06 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_offline_participants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='offline_absent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='offline_present',
        ),
        migrations.AddField(
            model_name='event',
            name='offline_participants',
            field=models.PositiveIntegerField(default=0, help_text='Total number of participants registered offline.'),
        ),
        migrations.CreateModel(
            name='OfflineAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.PositiveIntegerField(default=0)),
                ('absent', models.PositiveIntegerField(default=0)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offline_attendance', to='events.event')),
            ],
            options={
                'verbose_name': 'Offline Attendance',
                'verbose_name_plural': 'Offline Attendance',
            },
        ),
    ]
