# Generated by Django 6.0.7 on 2026-08-06 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_event_offline_absent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offlineattendance',
            name='absent',
        ),
    ]
